### ISSUE TITLE
Slash Command Function isn't running

### ISSUE THREAD

**Issue by mrkryptonlk** [GuriZenit/slash-bot-template#10]
`Error: Cannot find module 'node:events'
`
Do you have any idea about this? Nothings changed, Just imported to Glitch

**Comment by guritso** [comment]
> `Error: Cannot find module 'node:events'
> `
> Do you have any idea about this? Nothings changed, Just imported to Glitch

Did you fix it?
`edit:`_it was because `npm install` was not used. this [commit](https://github.com/GuriZenit/slash-bot-template/commit/877dbf6dfadfc4a2501059dda547dd0b8216fe0d) updated the [README.md](https://github.com/GuriZenit/slash-bot-template/blob/main/README.md) with it_

**Comment by mrkryptonlk** [comment]
Yes, Now I have another problem. I've successfully started the bot but the slash commands function ain't working

**Comment by guritso** [comment]
> Yes, Now I have another problem. I've successfully started the bot but the slash commands function ain't working
>  
Did you use the `node start.js`?  If yes the `add` has it been added or not? And is it functional or that's the problem?

**Comment by guritso** [comment]
> Yes, Now I have another problem. I've successfully started the bot but the slash commands function ain't working
>  
I just check Glitch, and found this:
```
No Node version was specified;
we are using default version 10.
You can change this in package.json:
https://glitch.happyfox.com/kb/article/59-can-i-change-the-version-of-node-js-my-project-uses/2:35 PM

node v10.24.1, with pnpm
```
This version of `discord.js` needs node `V16.9+`.
In this log they recomend this [article](https://glitch.happyfox.com/kb/article/59-can-i-change-the-version-of-node-js-my-project-uses/2:35) that's will tell you how to change the version there. And I recommend you to clone the repo again because some changes was made right after you clone it.
